baseURL = 'https://ezioleq.com/'
languageCode = 'en-us'
title = 'ezioverse'
theme = 'mini-mod'

hasCJKLanguage = true
defaultContentLanguage ='en'
paginate = 5

disqusShortname = 'ezioleq'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[params]
author = 'ezioleq'
bio = 'thoughts that escaped my head'
description = "Take a deep dive into my mind. This is My Space and My Universe. This is my dry as dust personal blog where I write posts... Take a look inside!"
image = 'https://ezioleq.com/images/avatar.png'

enableRSS = true
enableComments = true
showToc = true
showPowerBy = false
